/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiSixth;

import dbconnection.CreateTableDatabase;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import uiFifth.History;
import uiFirst.CityDao;
import uiFirst.CityDaoImpl;

/**
 *
 * @author HimelSaha
 */
public class Sixth extends javax.swing.JFrame {

    /**
     * Creates new form Sixth
     */
    public Sixth() {
        initComponents();
        this.getContentPane().setBackground(Color.PINK);
        txtNo.setBackground(Color.pink);
        btnEdit.setBackground(Color.cyan);
        btnDelete.setBackground(Color.red);
        lblStatus.setVisible(false);
        lblWarningEdit.setVisible(false);
        lblPhoneWarning.setVisible(false);
        lblEmailWarning.setVisible(false);
        lblDateFormat.setVisible(false);
        lblGenderWarning.setVisible(false);
        //new CreateTableDatabase().createTable();
        displayDataIntoTable();
    }
    CityDao dao = new CityDaoImpl();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassenger = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassport = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        lblWarningEdit = new javax.swing.JLabel();
        lblPhoneWarning = new javax.swing.JLabel();
        lblEmailWarning = new javax.swing.JLabel();
        lblGenderWarning = new javax.swing.JLabel();
        lblDateFormat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Passenger", "From", "To", "Date", "Class", "Seat", "Flight No.", "Email", "Gender", "Passport No.", "Phone"
            }
        ));
        tblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDisplay);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("No.");

        txtNo.setEditable(false);
        txtNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Passenger");

        txtPassenger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date");

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Gender");

        txtGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Passport No.");

        txtPassport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Phone");

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Orator Std", 2, 48)); // NOI18N
        jTextArea1.setRows(1
        );
        jTextArea1.setText("Travel History");
        jScrollPane1.setViewportView(jTextArea1);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 51, 255));
        lblStatus.setText("Refund Successful");

        lblWarningEdit.setForeground(new java.awt.Color(255, 0, 51));
        lblWarningEdit.setText("Fill in all fields to update");

        lblPhoneWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblPhoneWarning.setText("Enter valid number");

        lblEmailWarning.setForeground(new java.awt.Color(255, 51, 102));
        lblEmailWarning.setText("Enter valid email");

        lblGenderWarning.setForeground(new java.awt.Color(255, 0, 102));
        lblGenderWarning.setText("Enter valid gender");

        lblDateFormat.setForeground(new java.awt.Color(255, 0, 51));
        lblDateFormat.setText("Enter valid date\n DD/MM/YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addComponent(txtEmail)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(233, 233, 233)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDateFormat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPhoneWarning))
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWarningEdit)
                                    .addComponent(lblStatus))
                                .addGap(34, 34, 34))))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenderWarning)
                    .addComponent(lblEmailWarning))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGenderWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmailWarning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarningEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addGap(38, 38, 38)
                        .addComponent(btnDelete)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lblPhoneWarning)
                            .addComponent(lblDateFormat))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseClicked
        // TODO add your handling code here:
        lblStatus.setVisible(false);
        int i = tblDisplay.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        txtNo.setText(model.getValueAt(i, 0).toString());

        txtDate.setText(model.getValueAt(i, 4).toString());
        txtEmail.setText(model.getValueAt(i, 8).toString());
        txtPassport.setText(model.getValueAt(i, 10).toString());
        txtPhone.setText(model.getValueAt(i, 11).toString());
        txtGender.setText(model.getValueAt(i, 9).toString());
        txtPassenger.setText(model.getValueAt(i, 1).toString());
        lblWarningEdit.setVisible(false);

    }//GEN-LAST:event_tblDisplayMouseClicked

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (YesOrNo == 0) {
            String deleteId = txtNo.getText();
            dao.delete(deleteId);
            lblStatus.setText("Refund Successful");
            lblStatus.setVisible(true);
            displayDataIntoTable();
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        if (txtDate.getText().trim().isEmpty() || txtEmail.getText().trim().isEmpty() || txtGender.getText().trim().isEmpty() || txtNo.getText().trim().isEmpty() || txtPassenger.getText().trim().isEmpty() || txtPassport.getText().trim().isEmpty() || txtPhone.getText().trim().isEmpty() || lblPhoneWarning.isVisible()) {
            lblWarningEdit.setVisible(true);
        } else {

            if ((!(txtEmail.getText().contains("@"))) || (!(txtEmail.getText().contains(".com")))) {
                lblEmailWarning.setVisible(true);
                lblGenderWarning.setVisible(false);
                lblWarningEdit.setVisible(false);
            } else {

                if (((txtGender.getText().trim().equalsIgnoreCase("Male"))) || ((txtGender.getText().trim().equalsIgnoreCase("Female"))) || ((txtGender.getText().trim().equalsIgnoreCase("Other")))) {
                    if (txtPhone.getText().trim().length() != 11) {
                        lblPhoneWarning.setVisible(true);
                    } else {
                        //----------    DATE FUNCTION
                        try {
                            
                            String monthTest = txtDate.getText().substring(txtDate.getText().indexOf("/") + 1, 
                                    txtDate.getText().indexOf("/", txtDate.getText().indexOf("/") + 1));
                            
                            String yearTest = txtDate.getText().substring((txtDate.getText().indexOf("/", 
                                    txtDate.getText().indexOf("/") + 1)) + 1);
                            DateTimeFormatter iso = DateTimeFormatter.ISO_DATE;
                            
                            LocalDate testDate = LocalDate.parse(yearTest + "-" + monthTest + "-" + (txtDate.getText().substring(0, 
                                    txtDate.getText().indexOf("/"))), iso);
                            
                            
                            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                            LocalDate ld = LocalDate.parse(txtDate.getText(), format);
                            String dats = ld.format(format);
                            System.out.println(dats);
                            lblDateFormat.setVisible(false);
                        } catch(Exception e) {
                            lblDateFormat.setVisible(true);
                        }
                        if (!lblDateFormat.isVisible()) {
                            
                            try {
                            if ((Long.MAX_VALUE > Long.parseLong(txtPhone.getText().trim()))) {
                                lblWarningEdit.setVisible(false);
                                int YesOrNo = JOptionPane.showConfirmDialog(null, "Current data will be lost. Are you sure you want to update? ", "Confirm Update", JOptionPane.YES_NO_OPTION);

                                if (YesOrNo == 0) {
                                    dao.update(txtPassenger.getText().toUpperCase(), txtDate.getText(), txtEmail.getText().toLowerCase(), txtGender.getText(), txtPassport.getText(), txtPhone.getText(), txtNo.getText());
                                    lblStatus.setText("Update Successful");
                                    lblWarningEdit.setVisible(false);
                                    lblEmailWarning.setVisible(false);
                                    lblGenderWarning.setVisible(false);
                                    lblStatus.setVisible(true);
                                    displayDataIntoTable();
                                } else {

                                }
                            }
                        } catch (Exception g) {
                            lblPhoneWarning.setVisible(true);
                            lblWarningEdit.setVisible(false);
                        }
                        }

                    }

                } else {
                    lblGenderWarning.setVisible(true);
                    lblEmailWarning.setVisible(false);
                    lblWarningEdit.setVisible(false);
                }
            }

        }


    }//GEN-LAST:event_btnEditActionPerformed

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        // TODO add your handling code here:
        try {
            long i = Long.parseLong(txtPhone.getText().trim());
            lblPhoneWarning.setVisible(false);
        } catch (Exception e) {
            lblPhoneWarning.setVisible(true);
        }

    }//GEN-LAST:event_txtPhoneKeyTyped

    public void displayDataIntoTable() {
        List<History> list = dao.getList();
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        model.setNumRows(0);
        Object[] cols = new Object[12];

        for (int i = 0; i < list.size(); i++) {
            cols[0] = list.get(i).getSerials();
            cols[1] = list.get(i).getPassengers();
            cols[2] = list.get(i).getFroms();
            cols[3] = list.get(i).getTos();
            cols[4] = list.get(i).getDates();
            cols[5] = list.get(i).getClassess();
            cols[6] = list.get(i).getSeats();
            cols[7] = list.get(i).getFlightNos();
            cols[8] = list.get(i).getEmails();
            cols[9] = list.get(i).getGenders();
            cols[10] = list.get(i).getPassports();
            cols[11] = list.get(i).getPhones();
            model.addRow(cols);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sixth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sixth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDateFormat;
    private javax.swing.JLabel lblEmailWarning;
    private javax.swing.JLabel lblGenderWarning;
    private javax.swing.JLabel lblPhoneWarning;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWarningEdit;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtPassenger;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
